routes/web.php
Route::get('rekap-usulan/{id}/tahun/{year}', 'PublicController@programDetail');

// Registration Routes...
# Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
# Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group([
    'middleware'    => 'auth'
], function(){

//    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/dashboard', 'ReportController@index')->name('dashboard');

    Route::resource('guidance', 'GuidanceController');

    Route::resource('faqs', 'FaqController');

    Route::post('assets', 'AssetController@upload')->name('assets.upload');
    Route::get('assets/{path}', 'AssetController@view')->name('assets.view');

    Route::get('users/data', 'UserController@data')->name('users.data');
    Route::get('users/password', 'UserController@getFormPassword')->name('users.password.edit');
    Route::put('users/password/{userId}', 'UserController@updatePassword')->name('users.password.update');
    Route::resource('users', 'UserController');

    Route::resource('posts', 'PostController');

    Route::get('criteria/data', 'CriteriaController@data')->name('criteria.data');
    Route::get('criteria/rusun', 'CriteriaController@rusun')->name('criteria.rusun.index');
    Route::get('criteria/rusus', 'CriteriaController@rusus')->name('criteria.rusus.index');
    Route::get('criteria/swadaya', 'CriteriaController@swadaya')->name('criteria.swadaya.index');
    Route::get('criteria/ruk', 'CriteriaController@ruk')->name('criteria.ruk.index');
    Route::get('criteria/create', 'CriteriaController@create')->name('criteria.create');
    Route::get('criteria/{id}/download', 'CriteriaController@download')->name('criteria.download');

    Route::put('criteria/{id}', 'CriteriaController@update')->name('criteria.update');
    Route::post('criteria', 'CriteriaController@store')->name('criteria.store');
    Route::get('criteria/{id}/edit', 'CriteriaController@edit')->name('criteria.edit');
    Route::delete('criteria/{id}', 'CriteriaController@destroy')->name('criteria.destroy');
//    Route::resource('criteria', 'CriteriaController');

    Route::get('agencies/data', 'AgencyController@data')->name('agencies.data');
    Route::get('agencies/select', 'AgencyController@select2Data')->name('agencies.select');
    Route::get('agencies/combo-tree', 'AgencyController@comboTree')->name('agencies.combotree');
    Route::resource('agencies', 'AgencyController');

    Route::get('tematics/data', 'TematicController@data')->name('tematics.data');
    Route::get('tematics/select', 'TematicController@select2Data')->name('tematics.select');
    Route::resource('tematics', 'TematicController');

//    Route::get('programs/data', 'ProgramController@data')->name('programs.data');
    Route::get('programs/select', 'ProgramController@select2Data')->name('programs.select');
//    Route::resource('programs', 'ProgramController');

//    Route::get('recipients/data', 'RecipientController@data')->name('recipients.data');
    Route::get('recipients/select', 'RecipientController@select2Data')->name('recipients.select');
//    Route::resource('recipients', 'RecipientController');

    // Program Kegiatan
    Route::get('programs/data', 'ProgramController@data')->name('programs.data');
    Route::resource('programs', 'ProgramController');

    // Penerima Manfaat
    Route::get('recipients/data', 'RecipientController@data')->name('recipients.data');
    Route::resource('recipients', 'RecipientController');

    Route::get('regions/data', 'RegionController@data')->name('regions.data');
    Route::get('regions/select', 'RegionController@select2Data')->name('regions.select');
    Route::get('regions/combo-tree', 'RegionController@comboTree')->name('regions.combotree');
    Route::resource('regions', 'RegionController');


    Route::get('dwelling-plans/data', 'DwellingPlanController@data')->name('dwellings.plans.data');
    Route::post('dwelling-plans', 'DwellingPlanController@store')->name('dwellings.plans.store');
    Route::get('dwelling-plans/create', 'DwellingPlanController@create')->name('dwellings.plans.create');
    Route::delete('dwelling-plans/{dwelling}', 'DwellingPlanController@destroy')->name('dwellings.plans.destroy');
    Route::put('dwelling-plans/{dwelling}', 'DwellingPlanController@update')->name('dwellings.plans.update');
    Route::get('dwelling-plans/{dwelling}/edit', 'DwellingPlanController@edit')->name('dwellings.plans.edit');

    Route::get('surveyors/data', 'SurveyorController@data')->name('proposals.surveyors.data');
    Route::get('surveyors/create', 'SurveyorController@create')->name('proposals.surveyors.create');
    Route::post('surveyors', 'SurveyorController@store')->name('proposals.surveyors.store');
    Route::get('surveyors/{surveyors}/edit', 'SurveyorController@edit')->name('proposals.surveyors.edit');
    Route::put('surveyors/{surveyors}', 'SurveyorController@update')->name('proposals.surveyors.update');
    Route::delete('surveyors/{surveyors}', 'SurveyorController@destroy')->name('proposals.surveyors.destroy');

    Route::get('surveys/data', 'SurveyController@data')->name('proposals.surveys.data');
    Route::get('surveys/create', 'SurveyController@create')->name('proposals.surveys.create');
    Route::post('surveys', 'SurveyController@store')->name('proposals.surveys.store');
    Route::get('surveys/download/{proposal}', 'SurveyController@download');//->name('proposals.surveys.documents');
    Route::get('surveys/{surveys}/edit', 'SurveyController@edit')->name('proposals.surveys.edit');
    Route::put('surveys/{surveys}', 'SurveyController@update')->name('proposals.surveys.update');
    Route::delete('surveys/{surveys}', 'SurveyController@destroy')->name('proposals.surveys.destroy');

    Route::get('usulan/rusun/create', 'ProposalController@createProposalRusun')->name('proposals.create.rusun');
    Route::get('usulan/rusus/create', 'ProposalController@createProposalRusus')->name('proposals.create.rusus');
    Route::get('usulan/swadaya/create', 'ProposalController@createProposalSwadaya')->name('proposals.create.swadaya');
    Route::get('usulan/ruk/create', 'ProposalController@createProposalRuk')->name('proposals.create.ruk');
    Route::post('usulan', 'ProposalController@store')->name('proposals.store');

    Route::post('usulan/status', 'ProposalController@changeStatus')->name('proposals.statuses.update');

    Route::post('usulan/documents', 'ProposalController@document')->name('proposals.documents');
    Route::post('usulan/criterias', 'ProposalController@updatePivotCriteria')->name('proposals.criterias');
    Route::get('usulan/download/{proposal}/all', 'ProposalController@downloadAll')->name('proposals.documents.download.all');
    Route::get('usulan/download/{proposal}/{criteria}', 'ProposalController@download')->name('proposals.documents.download');
    Route::get('usulan/data', 'ProposalController@data')->name('proposals.data');
    Route::get('usulan', ['uses' => 'ProposalController@index', 'as' => 'proposals.index']);
    Route::put('usulan/{usulan}', 'ProposalController@update')->name('proposals.update');
    Route::get('usulan/{usulan}/edit', ['uses' => 'ProposalController@edit', 'as' => 'proposals.edit']);
    Route::delete('usulan/{usulan}', ['uses' => 'ProposalController@destroy', 'as' => 'proposals.destroy']);
    Route::get('usulan/{usulan}/status/edit', ['uses' => 'ProposalController@editStatus'])->name('proposals.status.edit');
    Route::put('usulan/{usulan}/status', ['uses' => 'ProposalController@updateStatus'])->name('proposals.status.update');

    Route::post('comments', 'CommentController@store')->name('comments.store');

    // Shortlist
    Route::get('usulan/{id}/shortlist', 'ShortlistController@create')->name('shortlists.create');
    Route::get('shortlist/data', 'ShortlistController@data')->name('shortlists.data');
    Route::get('shortlist', 'ShortlistController@index')->name('shortlists.index');
    Route::post('shortlist', 'ShortlistController@store')->name('shortlists.store');
    Route::get('shortlist/{proposal}/edit', 'ShortlistController@edit')->name('shortlists.edit');
    Route::put('shortlist', 'ShortlistController@store')->name('shortlists.update');
    Route::get('shortlist/view', 'ShortlistController@view')->name('shortlists.view');
    Route::delete('shortlist', 'ShortlistController@destroy')->name('shortlists.destroy');

    // SK Penetapan
    Route::get('sk-penetapan', 'DecreeController@index')->name('decrees.index');
    Route::get('usulan/{id}/sk-penetapan', 'DecreeController@create')->name('decrees.create');
    Route::get('sk-penetapan/data', 'DecreeController@data')->name('decrees.data');
    Route::post('sk-penetapan', 'DecreeController@store')->name('decrees.store');
    Route::get('sk-penetapan/{proposal}/edit', 'DecreeController@edit')->name('decrees.edit');
    Route::put('sk-penetapan', 'DecreeController@store')->name('decrees.update');
    Route::delete('sk-penetapan/{proposal}', 'DecreeController@destroy')->name('decrees.destroy');
    Route::get('sk-penetapan/{proposal}/download', 'DecreeController@download')->name('decrees.download');

    // eprofile
     /* Route::get('usulan/{id}/eprofile', 'EprofileController@create')->name('eprofile.create');
    Route::get('eprofile', 'EprofileController@index')->name('eprofile.index');
    Route::post('eprofile', 'EprofileController@store')->name('eprofile.store');
    Route::get('eprofile/{id}/edit', 'EprofileController@edit')->name('eprofile.edit');

app/Models/Recipient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Recipient
 *
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Recipient whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Recipient whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Recipient whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Recipient whereUpdatedAt($value)
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Proposal[] $proposals
 * @property int $unit_id
 * @property string $abbreviation
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Recipient whereAbbreviation($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Recipient whereUnitId($value)
 * @property-read \App\Models\Unit $unit
 */
class Recipient extends Model
{
    protected $fillable = ['unit_id', 'name', 'abbreviation'];

    public function proposals()
    {
        return $this->hasMany(Proposal::class);
    }

    public function unit()
    {
        return $this->belongsTo(Unit::class);
    }
}

app/Http/Controllers/RecipientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Recipient;
use App\Models\Unit;
use Illuminate\Http\Request;

class RecipientController extends Controller
{
    protected $identifier = 'penerima';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (\Gate::denies('do-master')) {
            abort(404);
        }

        $title = 'Penerima Manfaat';

        return view('recipient.index', compact('title'))
            ->with('identifier', $this->identifier);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     * @throws \Throwable
     */
    public function create(Request $request)
    {
        $type = $request->get('type');

        if ($request->ajax()) {

            $typeTitle = title_case($type);

            return response()->json([
                'title'  => "Penerima Manfaat {$typeTitle} Baru",
                'body'   => view('recipient.modal.create')
                    ->with([
                        'identifier' => $this->identifier,
                        'type'       => $type
                    ])
                    ->render(),
                'footer' => view('recipient.modal.footer')
                    ->with([
                        'identifier' => $this->identifier,
                        'type'       => $type
                    ])
                    ->render()
            ]);
        } else {
            return view('recipient.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = validator($request->all(), [
            'name'         => 'required',
            'abbreviation' => 'required',
        ]);

        if ($validator->fails()) {
            if ($request->ajax()) {
                return response()->json($validator->errors(), 400);
            }
        }

        $type = $request->get('type');

        return Recipient::create([
            'unit_id'      => Unit::whereSlug($type)->first()->id,
            'name'         => $request->get('name'),
            'abbreviation' => $request->get('abbreviation')
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Recipient $recipient
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Recipient $recipient)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param         $id
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     * @throws \Throwable
     *
     */
    public function edit($id, Request $request)
    {
        $recipient = Recipient::with('unit')->find($id);

        if ($request->ajax()) {
            return response()->json([
                'title'  => "Edit penerima manfaat",
                'body'   => view('recipient.modal.edit', compact('recipient'))
                    ->with([
                        'identifier' => $this->identifier,
                        'type'       => $recipient->unit->slug

                    ])
                    ->render(),
                'footer' => view('recipient.modal.footer')
                    ->with([
                        'identifier' => $this->identifier,
                        'type'       => $recipient->unit->slug
                    ])
                    ->render()
            ]);
        } else {
            return view('recipient.edit');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Recipient $recipient
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = validator($request->all(), [
            'name'         => 'required',
            'abbreviation' => 'required',
        ]);

        if ($validator->fails()) {
            if ($request->ajax()) {
                return response()->json($validator->errors(), 400);
            }
        }

        $recipient = Recipient::find($id);

        $recipient->name = $request->get('name');
        $recipient->abbreviation = $request->get('abbreviation');
        $recipient->save();

        if ($request->ajax()) {
            return response()->json([]);
        }

        return redirect()->route('recipients.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Recipient $recipient
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return Recipient::destroy($id);
    }

    public function select2Data(Request $request)
    {
        $q = strtolower($request->get('q'));
        $unit_id = $request->get('unit_id', 0);

        if ($unit_id == 0) {
            return Recipient::where(\DB::raw('LOWER(name)'), 'like', "$q%")
                ->get();
        } else {

            return Recipient::where(\DB::raw('LOWER(name)'), 'like', "%$q%")
                ->whereUnitId($unit_id)->get();
        }
    }

    public function data(Request $request)
    {
        $type = $request->get('type');

        $unit = Unit::whereSlug($type)->first();

        $builder = Recipient::whereUnitId($unit->id);

        return \Datatables::of($builder)
            ->addColumn('action', function ($data) use ($type) {
                return view('recipient.action')
                    ->with([
                        'edit_link'   => route('recipients.edit', [$data->id]),
                        'delete_link' => route('recipients.destroy', [$data->id]),
                        'identifier'  => $this->identifier,
                        'type'        => $type
                    ])
                    ->render();
            })
            ->make(true);
    }
}

resources/views/recipient/action.blade.php
<div class="btn-group btn-group-xs pull-right">
    <button type="button" class="btn btn-warning" onclick="editForm(this)"
            data-form="{{$edit_link}}">
        <i class="fa fa-pencil"></i>
        <span class="hidden-xs hidden-sm">&nbsp; Edit</span>
    </button>
    <button type="button" class="btn btn-danger" onclick="deleteForm(this)"
            data-link="{{$delete_link}}"
            data-identifier="{{$identifier . $type}}">

        <i class="fa fa-trash"></i>
        <span class="hidden-xs hidden-sm">&nbsp; Delete</span>
    </button>
</div>

resources/views/recipient/create.blade.php
@extends('layout.main')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="portlet light portlet-datatable">
                <div class="portlet-title">
                    <div class="caption">
                        <div class="caption-subject">Users</div>
                    </div>
                    <div class="actions">

                    </div>
                </div>
                <div class="portlet-body">
                    @include('recipient.modal.create')
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/recipient/edit.blade.php
@extends('layout.main')

@section('styles')
@stop

@section('style')
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="portlet light portlet-datatable">
                <div class="portlet-title">
                    <div class="caption">
                        <div class="caption-subject">Edit user</div>
                    </div>
                    <div class="actions">

                    </div>
                </div>
                <div class="portlet-body">
                    @include('recipient.modal.edit')
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
@stop

@section('script')
@stop

resources/views/recipient/index.blade.php
@extends('layout.main')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="portlet light portlet-datatable">
                <div class="portlet-title tabbable-line">
                    {{--<div class="caption">
                        <div class="caption-subject">Program Kegiatan</div>
                    </div>--}}

                    <ul class="nav nav-tabs pull-left">
                        <li class="active">
                            <a href="#rusun" data-toggle="tab">Rusun</a>
                        </li>

                        <li class="">
                            <a href="#rusus" data-toggle="tab">Rusus</a>
                        </li>

                        <li class="">
                            <a href="#ruk" data-toggle="tab">RUK</a>
                        </li>

                        <li class="">
                            <a href="#swadaya" data-toggle="tab">Swadaya</a>
                        </li>
                    </ul>

                   {{-- <div class="actions">
                        <button class="btn btn-primary"
                                data-toggle="modal"
                                data-target="#general-modal"
                                data-backdrop="static"
                                data-keyboard="false"
                                id="{{$identifier}}-trigger-modal">
                            <i class="fa fa-plus"></i>&nbsp; Tambah Program
                        </button>
                    </div>--}}
                </div>
                <div class="portlet-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="rusun">
                            @include('recipient.tab-content', ['type' => 'rusun'])
                        </div>

                        <div class="tab-pane" id="rusus">
                            @include('recipient.tab-content', ['type' => 'rusus'])
                        </div>

                        <div class="tab-pane" id="ruk">
                            @include('recipient.tab-content', ['type' => 'ruk'])
                        </div>

                        <div class="tab-pane" id="swadaya">
                            @include('recipient.tab-content', ['type' => 'swadaya'])
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@include('_component.select2')
@include('_component.datatables')

@push('scripts')
<script src="{{asset('js/simpleUpload.min.js')}}"></script>
@endpush

@push('script')
<script>

    $(document).ready(function(){
        // Re adjust table size in tab content
        // https://github.com/DataTables/Responsive/issues/40
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            $($.fn.dataTable.tables(true)).css('width', '100%');
            $($.fn.dataTable.tables(true)).DataTable().columns.adjust().draw();
        });

    });


</script>
@endpush

resources/views/recipient/tab-content.blade.php
<div class="row margin-bottom-15">
    <div class="col-sm-12">
        <button class="btn btn-primary pull-right"
                data-toggle="modal"
                data-target="#general-modal"
                data-backdrop="static"
                data-keyboard="false"
                id="{{$identifier . $type}}-trigger-modal">
            <i class="fa fa-plus"></i>&nbsp; Tambah Penerima Manfaat {{title_case($type)}}
        </button>
    </div>
</div>
<table class="table table-striped table-bordered table-condensed" id="{{$identifier. $type}}-datatables">
    <thead>
    <tr>
        <th>Program Kegiatan</th>
        <th>Singkatan</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
</table>

@push('script')
<script>
    $('#{{$identifier . $type}}-datatables').DataTable({
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{route('recipients.data')}}",
            data: function(d) {
                d.type = '{{$type}}'
            }
        },
        columns: [
            {data: 'name', name: 'name'},
            {data: 'abbreviation', name: 'abbreviation'},
            {data: 'action', name: 'action', searchable: false, orderable: false},
        ],
    });

    $('#{{$identifier . $type}}-trigger-modal').click(function () {

        showGeneralModal('{{route('recipients.create')}}?type={{$type}}');
    });
</script>
@endpush