routes/web.php
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group([
    'middleware'    => 'auth'
], function(){

//    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/dashboard', 'ReportController@index')->name('dashboard');

    Route::resource('guidance', 'GuidanceController');

    Route::resource('faqs', 'FaqController');

    Route::post('assets', 'AssetController@upload')->name('assets.upload');
    Route::get('assets/{path}', 'AssetController@view')->name('assets.view');

    Route::get('users/data', 'UserController@data')->name('users.data');
    Route::get('users/password', 'UserController@getFormPassword')->name('users.password.edit');
    Route::put('users/password/{userId}', 'UserController@updatePassword')->name('users.password.update');
    Route::resource('users', 'UserController');

    Route::resource('posts', 'PostController');

    Route::get('criteria/data', 'CriteriaController@data')->name('criteria.data');
    Route::get('criteria/rusun', 'CriteriaController@rusun')->name('criteria.rusun.index');
    Route::get('criteria/rusus', 'CriteriaController@rusus')->name('criteria.rusus.index');
    Route::get('criteria/swadaya', 'CriteriaController@swadaya')->name('criteria.swadaya.index');
    Route::get('criteria/ruk', 'CriteriaController@ruk')->name('criteria.ruk.index');
    Route::get('criteria/create', 'CriteriaController@create')->name('criteria.create');
    Route::get('criteria/{id}/download', 'CriteriaController@download')->name('criteria.download');

    Route::put('criteria/{id}', 'CriteriaController@update')->name('criteria.update');
    Route::post('criteria', 'CriteriaController@store')->name('criteria.store');
    Route::get('criteria/{id}/edit', 'CriteriaController@edit')->name('criteria.edit');
    Route::delete('criteria/{id}', 'CriteriaController@destroy')->name('criteria.destroy');
//    Route::resource('criteria', 'CriteriaController');

    Route::get('agencies/data', 'AgencyController@data')->name('agencies.data');
    Route::get('agencies/select', 'AgencyController@select2Data')->name('agencies.select');
    Route::get('agencies/combo-tree', 'AgencyController@comboTree')->name('agencies.combotree');
    Route::resource('agencies', 'AgencyController');

    Route::get('tematics/data', 'TematicController@data')->name('tematics.data');
    Route::get('tematics/select', 'TematicController@select2Data')->name('tematics.select');
    Route::resource('tematics', 'TematicController');

//    Route::get('programs/data', 'ProgramController@data')->name('programs.data');
    Route::get('programs/select', 'ProgramController@select2Data')->name('programs.select');
//    Route::resource('programs', 'ProgramController');

//    Route::get('recipients/data', 'RecipientController@data')->name('recipients.data');
    Route::get('recipients/select', 'RecipientController@select2Data')->name('recipients.select');
//    Route::resource('recipients', 'RecipientController');

    // Program Kegiatan
    Route::get('programs/data', 'ProgramController@data')->name('programs.data');
    Route::resource('programs', 'ProgramController');

    // Penerima Manfaat
    Route::get('recipients/data', 'RecipientController@data')->name('recipients.data');
    Route::resource('recipients', 'RecipientController');

    Route::get('regions/data', 'RegionController@data')->name('regions.data');
    Route::get('regions/select', 'RegionController@select2Data')->name('regions.select');
    Route::get('regions/combo-tree', 'RegionController@comboTree')->name('regions.combotree');
    Route::resource('regions', 'RegionController');


    Route::get('dwelling-plans/data', 'DwellingPlanController@data')->name('dwellings.plans.data');
    Route::post('dwelling-plans', 'DwellingPlanController@store')->name('dwellings.plans.store');
    Route::get('dwelling-plans/create', 'DwellingPlanController@create')->name('dwellings.plans.create');
    Route::delete('dwelling-plans/{dwelling}', 'DwellingPlanController@destroy')->name('dwellings.plans.destroy');
    Route::put('dwelling-plans/{dwelling}', 'DwellingPlanController@update')->name('dwellings.plans.update');
    Route::get('dwelling-plans/{dwelling}/edit', 'DwellingPlanController@edit')->name('dwellings.plans.edit');

    Route::get('surveyors/data', 'SurveyorController@data')->name('proposals.surveyors.data');
    Route::get('surveyors/create', 'SurveyorController@create')->name('proposals.surveyors.create');
    Route::post('surveyors', 'SurveyorController@store')->name('proposals.surveyors.store');
    Route::get('surveyors/{surveyors}/edit', 'SurveyorController@edit')->name('proposals.surveyors.edit');
    Route::put('surveyors/{surveyors}', 'SurveyorController@update')->name('proposals.surveyors.update');
    Route::delete('surveyors/{surveyors}', 'SurveyorController@destroy')->name('proposals.surveyors.destroy');

    Route::get('surveys/data', 'SurveyController@data')->name('proposals.surveys.data');
    Route::get('surveys/create', 'SurveyController@create')->name('proposals.surveys.create');
    Route::post('surveys', 'SurveyController@store')->name('proposals.surveys.store');
    Route::get('surveys/download/{proposal}', 'SurveyController@download');//->name('proposals.surveys.documents');
    Route::get('surveys/{surveys}/edit', 'SurveyController@edit')->name('proposals.surveys.edit');
    Route::put('surveys/{surveys}', 'SurveyController@update')->name('proposals.surveys.update');
    Route::delete('surveys/{surveys}', 'SurveyController@destroy')->name('proposals.surveys.destroy');

    Route::get('usulan/rusun/create', 'ProposalController@createProposalRusun')->name('proposals.create.rusun');
    Route::get('usulan/rusus/create', 'ProposalController@createProposalRusus')->name('proposals.create.rusus');
    Route::get('usulan/swadaya/create', 'ProposalController@createProposalSwadaya')->name('proposals.create.swadaya');
    Route::get('usulan/ruk/create', 'ProposalController@createProposalRuk')->name('proposals.create.ruk');
    Route::post('usulan', 'ProposalController@store')->name('proposals.store');

    Route::post('usulan/status', 'ProposalController@changeStatus')->name('proposals.statuses.update');

    Route::post('usulan/documents', 'ProposalController@document')->name('proposals.documents');
    Route::post('usulan/criterias', 'ProposalController@updatePivotCriteria')->name('proposals.criterias');
    Route::get('usulan/download/{proposal}/all', 'ProposalController@downloadAll')->name('proposals.documents.download.all');
    Route::get('usulan/download/{proposal}/{criteria}', 'ProposalController@download')->name('proposals.documents.download');
    Route::get('usulan/data', 'ProposalController@data')->name('proposals.data');
    Route::get('usulan', ['uses' => 'ProposalController@index', 'as' => 'proposals.index']);
    Route::put('usulan/{usulan}', 'ProposalController@update')->name('proposals.update');
    Route::get('usulan/{usulan}/edit', ['uses' => 'ProposalController@edit', 'as' => 'proposals.edit']);
    Route::delete('usulan/{usulan}', ['uses' => 'ProposalController@destroy', 'as' => 'proposals.destroy']);
    Route::get('usulan/{usulan}/status/edit', ['uses' => 'ProposalController@editStatus'])->name('proposals.status.edit');
    Route::put('usulan/{usulan}/status', ['uses' => 'ProposalController@updateStatus'])->name('proposals.status.update');

    Route::post('comments', 'CommentController@store')->name('comments.store');

    // Shortlist
    Route::get('usulan/{id}/shortlist', 'ShortlistController@create')->name('shortlists.create');
    Route::get('shortlist/data', 'ShortlistController@data')->name('shortlists.data');
    Route::get('shortlist', 'ShortlistController@index')->name('shortlists.index');
    Route::post('shortlist', 'ShortlistController@store')->name('shortlists.store');
    Route::get('shortlist/{proposal}/edit', 'ShortlistController@edit')->name('shortlists.edit');
    Route::put('shortlist', 'ShortlistController@store')->name('shortlists.update');
    Route::get('shortlist/view', 'ShortlistController@view')->name('shortlists.view');
    Route::delete('shortlist', 'ShortlistController@destroy')->name('shortlists.destroy');

    // SK Penetapan
    Route::get('sk-penetapan', 'DecreeController@index')->name('decrees.index');
    Route::get('usulan/{id}/sk-penetapan', 'DecreeController@create')->name('decrees.create');
    Route::get('sk-penetapan/data', 'DecreeController@data')->name('decrees.data');
    Route::post('sk-penetapan', 'DecreeController@store')->name('decrees.store');
    Route::get('sk-penetapan/{proposal}/edit', 'DecreeController@edit')->name('decrees.edit');
    Route::put('sk-penetapan', 'DecreeController@store')->name('decrees.update');
    Route::delete('sk-penetapan/{proposal}', 'DecreeController@destroy')->name('decrees.destroy');
    Route::get('sk-penetapan/{proposal}/download', 'DecreeController@download')->name('decrees.download');

    // eprofile
     /* Route::get('usulan/{id}/eprofile', 'EprofileController@create')->name('eprofile.create');
    Route::get('eprofile', 'EprofileController@index')->name('eprofile.index');
    Route::post('eprofile', 'EprofileController@store')->name('eprofile.store');
    Route::get('eprofile/{id}/edit', 'EprofileController@edit')->name('eprofile.edit');
    Route::put('eprofile', 'EprofileController@store')->name('eprofile.update');
    Route::delete('eprofile', 'EprofileController@destroy')->name('eprofile.destroy');
    */
    Route::get('eprofile/data', 'EprofileController@data')->name('eprofile.data');
    Route::get('eprofile/advanced-excel', 'EprofileController@showFormAdvancedExcel');
    Route::get('eprofile/advanced-excel/rincian', 'EprofileController@exportRincian');
    Route::get('eprofile/advanced-excel/rekap', 'EprofileController@exportRekap');
    Route::resource('eprofile', 'EprofileController');

    Route::get('laporan', 'ReportController@index')->name('reports.index');

app/Models/Region.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

/**
 * App\Models\Region
 *
 * @mixin \Eloquent
 * @property int $id
 * @property int $parent_id
 * @property string $name
 * @property int $level
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereLevel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereParentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereUpdatedAt($value)
 * @property-read \App\Models\Agency $agency
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Region[] $children
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\DwellingPlan[] $dwellingPlans
 * @property-read \App\Models\Region $parent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\RegionProfile[] $profiles
 * @property int $_lft
 * @property int $_rgt
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region d()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereLft($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Region whereRgt($value)
 * @property int $order
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region whereOrder($value)
 */
class Region extends Model
{
    use NodeTrait;

    protected $primaryKey = 'id';

    protected $fillable = ['parent_id', 'name', 'level', 'order'];

    public function agency() {
        return $this->hasOne(Agency::class);
    }

    public function dwellingPlans()
    {
        return $this->hasMany(DwellingPlan::class);
    }

    public function profiles()
    {
        return $this->hasMany(RegionProfile::class);

    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }
}

resources/views/region/action.blade.php
<div class="btn-group btn-group-xs pull-right">
   {{-- <a class="btn btn-warning" href="{{route('regions.profiles.index', [$region['id']])}}">
        <i class="fa fa-user"></i>
        <span class="hidden-xs hidden-sm">&nbsp; Profile</span>
    </a>--}}

    <button type="button" class="btn btn-warning" onclick="editForm(this)"
            data-id="{{$region['id']}}"
            data-form="{{route('regions.edit', $region['id'])}}">
        <i class="fa fa-pencil"></i>
        <span class="hidden-xs hidden-sm">&nbsp; Edit</span>
    </button>

    <button type="button" class="btn btn-danger" onclick="deleteRegion(this)"
            data-link="{{route('regions.destroy', [$region['id']])}}"
            data-identifier="{{$identifier}}">
        <i class="fa fa-trash"></i>
    </button>
</div>

{{-- Ini buat profile provinsi --}}
@if(!is_null($year))
    <a class="btn btn-warning btn-xs pull-right" href="{{route('regions.profiles.index', $region['id'])}}?year={{$year}}">
        <i class="fa fa-pencil"></i>
        <span class="hidden-xs hidden-sm">&nbsp; Edit</span>
    </a>
@endif

resources/views/region/create.blade.php
@extends('layout.main')

@section('styles')
@stop

@section('style')
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="portlet light portlet-datatable">
                <div class="portlet-title">
                    <div class="caption">
                        <div class="caption-subject">FAQ</div>
                    </div>
                    <div class="actions">

                    </div>
                </div>
                <div class="portlet-body">
                    @include('region.modal.create')
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
@stop

@section('script')
@stop

resources/views/region/edit.blade.php
@extends('layout.main')

@section('styles')
@stop

@section('style')
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="portlet light portlet-datatable">
                <div class="portlet-title">
                    <div class="caption">
                        <div class="caption-subject">Edit Wilayah</div>
                    </div>
                    <div class="actions">

                    </div>
                </div>
                <div class="portlet-body">
                    @include('region.modal.edit')
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
@stop

@section('script')
@stop

resources/views/region/index.blade.php
@extends('layout.main')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="portlet light portlet-datatable">
                <div class="portlet-title">
                    <div class="caption">
                        <div class="caption-subject">Wilayah</div>
                    </div>
                    <div class="actions">
                        <button class="btn btn-primary"
                                data-toggle="modal"
                                data-target="#general-modal"
                                data-backdrop="static"
                                data-keyboard="false"
                                id="{{$identifier}}-trigger-modal">
                            <i class="fa fa-plus"></i>&nbsp; Tambah wilayah
                        </button>
                    </div>
                </div>
                <div class="portlet-body">
                    {{--<div class="row form-inline margin-bottom-15" id="filter">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="unit">Provinsi:</label>
                                <select name="unit" id="unit" class="form-control input-sm ">
                                    <option value="0" selected>Semua</option>

                                </select>
                            </div>

                            <div class="form-group">
                                <label for="unit">Kabupaten:</label>
                                <select name="unit" id="unit" class="form-control input-sm ">
                                    <option value="0" selected>Semua</option>

                                </select>
                            </div>

                            <div class="form-group">
                                <label for="unit">Kecamatan:</label>
                                <select name="unit" id="unit" class="form-control input-sm ">
                                    <option value="0" selected>Semua</option>

                                </select>
                            </div>
                        </div>

                    </div>--}}

                    <table class="" id="{{$identifier}}-datatables">

                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@include('_component.select2')
@include('_component.easyui')

@push('styles')
<link rel="stylesheet" href="{{asset('components/sweetalert2/dist/sweetalert2.css')}}">
@endpush

@push('scripts')
<script src="{{asset('components/sweetalert2/dist/sweetalert2.min.js')}}"></script>
<script src="{{asset('js/simpleUpload.min.js')}}"></script>
@endpush

@push('script')
<script>
    $('#{{$identifier}}-datatables').treegrid({
        method: "GET",
        url: "{{route('regions.data')}}?level=4",
        idField: "id",
        treeField: "name",
        lines: true,
        striped: true,
        columns: [[
            {title:'Nama',field:'name'},
            {title:'Level',field:'level',width:280},
            {title:' ',field:'action'}
        ]]
    });

    $('#{{$identifier}}-trigger-modal').click(function () {

        showGeneralModal('{{route('regions.create')}}');

    });

    function saveRegion(dom) {

        var identifier = $(dom).data('identifier');

        var id = $(dom).data('id');

        var $identifier = $('#' + identifier);

        var url = $identifier.attr('action');

        $.ajax({
            type: "POST",
            url: url,
            data: $identifier.serialize(), // serializes the form's elements.
            success: function (data) {

                console.log(data);

                // close modal
                $('#general-modal').modal('hide');

                // reload datatables\
                if(data.parent_id !== null) {
                    $('#' + identifier + '-datatables').treegrid('reload', data.parent_id);
                } else {
                    $('#' + identifier + '-datatables').treegrid('reload');
                }

                // kasih centang gede
                swal({
                    title: 'Good job!',
                    text: 'You add one data!',
                    timer: 2000,
                    type: 'success'
                });


            },
            error: function (jqXHR, textStatus, errorThrown) {

                $identifier.find('.form-group').removeClass('has-error');
                $identifier.find('.form-group').find('.help-block').html('');

                var data = $.parseJSON(jqXHR.responseText);

                $.each(data, function (item, errors) {

                    var html = '<ul class="list-unstyled">';

                    $.each(errors, function (index, error) {

                        html += '<li>' + error + '</li>';
                    });

                    html += '</ul>';

                    $('#help-block-' + item).html(html);
                    $('#help-block-' + item).parent().addClass('has-error');

                });
            }
        });
    }

    function deleteRegion(dom) {

        var url = $(dom).data('link');
        var identifier = $(dom).data('identifier');



        swal({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then(function () {

            $.ajax({
                type: "DELETE",
                url: url,
                data: {
                    _token: $("meta[name=csrf-token]").attr('content')
                }, // serializes the form's elements.
                success: function (data) {

                    console.log(data)

                    // reload datatables\
                    if(data.parent_id !== null) {
                        $('#' + identifier + '-datatables').treegrid('reload', data.parent_id);
                    } else {
                        $('#' + identifier + '-datatables').treegrid('reload');
                    }

                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )

                }
            });
        })
    }
</script>
@endpush