routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PublicController@index')->name('home');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout')->middleware('auth');

# Profile
Route::get('profile', 'UserController@showProfile')->name('profile.index')->middleware('auth');
Route::put('profile', 'UserController@updateProfile')->name('profile.update')->middleware('auth');
Route::put('profile/password', 'UserController@updateProfilePassword')->name('profile.pass')->middleware('auth');

#
Route::get('pedoman', 'PublicController@pedoman')->name('public.pedoman');
Route::get('pedoman/{id}/unduh', 'PublicController@downloadPedoman')->name('public.pedoman.download');
Route::get('faq', 'PublicController@faq')->name('public.faq');
Route::get('kontak', 'PublicController@aboutUs')->name('public.about');
Route::get('program', 'PublicController@program');
Route::get('rekap-usulan', 'PublicController@program');
Route::get('rekap-usulan/chart/data', 'PublicController@programChartData')->name('program.chart.data');
Route::get('rekap-usulan/{year}', 'PublicController@programYear')->name('public.program.year');
Route::get('rekap-usulan/{id}/tahun/{year}', 'PublicController@programDetail');

// Registration Routes...
# Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
# Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group([
    'middleware'    => 'auth'
], function(){

//    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/dashboard', 'ReportController@index')->name('dashboard');

    Route::resource('guidance', 'GuidanceController');

    Route::resource('faqs', 'FaqController');

    Route::post('assets', 'AssetController@upload')->name('assets.upload');
    Route::get('assets/{path}', 'AssetController@view')->name('assets.view');

    Route::get('users/data', 'UserController@data')->name('users.data');
    Route::get('users/password', 'UserController@getFormPassword')->name('users.password.edit');
    Route::put('users/password/{userId}', 'UserController@updatePassword')->name('users.password.update');
    Route::resource('users', 'UserController');

    Route::resource('posts', 'PostController');

    Route::get('criteria/data', 'CriteriaController@data')->name('criteria.data');
    Route::get('criteria/rusun', 'CriteriaController@rusun')->name('criteria.rusun.index');
    Route::get('criteria/rusus', 'CriteriaController@rusus')->name('criteria.rusus.index');
    Route::get('criteria/swadaya', 'CriteriaController@swadaya')->name('criteria.swadaya.index');
    Route::get('criteria/ruk', 'CriteriaController@ruk')->name('criteria.ruk.index');
    Route::get('criteria/create', 'CriteriaController@create')->name('criteria.create');
    Route::get('criteria/{id}/download', 'CriteriaController@download')->name('criteria.download');

    Route::put('criteria/{id}', 'CriteriaController@update')->name('criteria.update');
    Route::post('criteria', 'CriteriaController@store')->name('criteria.store');
    Route::get('criteria/{id}/edit', 'CriteriaController@edit')->name('criteria.edit');
    Route::delete('criteria/{id}', 'CriteriaController@destroy')->name('criteria.destroy');
//    Route::resource('criteria', 'CriteriaController');

    Route::get('agencies/data', 'AgencyController@data')->name('agencies.data');
    Route::get('agencies/select', 'AgencyController@select2Data')->name('agencies.select');
    Route::get('agencies/combo-tree', 'AgencyController@comboTree')->name('agencies.combotree');
    Route::resource('agencies', 'AgencyController');

    Route::get('tematics/data', 'TematicController@data')->name('tematics.data');
    Route::get('tematics/select', 'TematicController@select2Data')->name('tematics.select');
    Route::resource('tematics', 'TematicController');

//    Route::get('programs/data', 'ProgramController@data')->name('programs.data');
    Route::get('programs/select', 'ProgramController@select2Data')->name('programs.select');
//    Route::resource('programs', 'ProgramController');

//    Route::get('recipients/data', 'RecipientController@data')->name('recipients.data');
    Route::get('recipients/select', 'RecipientController@select2Data')->name('recipients.select');
//    Route::resource('recipients', 'RecipientController');

    // Program Kegiatan
    Route::get('programs/data', 'ProgramController@data')->name('programs.data');
    Route::resource('programs', 'ProgramController');

    // Penerima Manfaat
    Route::get('recipients/data', 'RecipientController@data')->name('recipients.data');
    Route::resource('recipients', 'RecipientController');

    Route::get('regions/data', 'RegionController@data')->name('regions.data');
    Route::get('regions/select', 'RegionController@select2Data')->name('regions.select');
    Route::get('regions/combo-tree', 'RegionController@comboTree')->name('regions.combotree');
    Route::resource('regions', 'RegionController');


    Route::get('dwelling-plans/data', 'DwellingPlanController@data')->name('dwellings.plans.data');
    Route::post('dwelling-plans', 'DwellingPlanController@store')->name('dwellings.plans.store');
    Route::get('dwelling-plans/create', 'DwellingPlanController@create')->name('dwellings.plans.create');
    Route::delete('dwelling-plans/{dwelling}', 'DwellingPlanController@destroy')->name('dwellings.plans.destroy');
    Route::put('dwelling-plans/{dwelling}', 'DwellingPlanController@update')->name('dwellings.plans.update');
    Route::get('dwelling-plans/{dwelling}/edit', 'DwellingPlanController@edit')->name('dwellings.plans.edit');

    Route::get('surveyors/data', 'SurveyorController@data')->name('proposals.surveyors.data');
    Route::get('surveyors/create', 'SurveyorController@create')->name('proposals.surveyors.create');
    Route::post('surveyors', 'SurveyorController@store')->name('proposals.surveyors.store');
    Route::get('surveyors/{surveyors}/edit', 'SurveyorController@edit')->name('proposals.surveyors.edit');
    Route::put('surveyors/{surveyors}', 'SurveyorController@update')->name('proposals.surveyors.update');
    Route::delete('surveyors/{surveyors}', 'SurveyorController@destroy')->name('proposals.surveyors.destroy');

    Route::get('surveys/data', 'SurveyController@data')->name('proposals.surveys.data');
    Route::get('surveys/create', 'SurveyController@create')->name('proposals.surveys.create');
    Route::post('surveys', 'SurveyController@store')->name('proposals.surveys.store');
    Route::get('surveys/download/{proposal}', 'SurveyController@download');//->name('proposals.surveys.documents');
    Route::get('surveys/{surveys}/edit', 'SurveyController@edit')->name('proposals.surveys.edit');
    Route::put('surveys/{surveys}', 'SurveyController@update')->name('proposals.surveys.update');
    Route::delete('surveys/{surveys}', 'SurveyController@destroy')->name('proposals.surveys.destroy');

    Route::get('usulan/rusun/create', 'ProposalController@createProposalRusun')->name('proposals.create.rusun');
    Route::get('usulan/rusus/create', 'ProposalController@createProposalRusus')->name('proposals.create.rusus');
    Route::get('usulan/swadaya/create', 'ProposalController@createProposalSwadaya')->name('proposals.create.swadaya');
    Route::get('usulan/ruk/create', 'ProposalController@createProposalRuk')->name('proposals.create.ruk');
    Route::post('usulan', 'ProposalController@store')->name('proposals.store');

    Route::post('usulan/status', 'ProposalController@changeStatus')->name('proposals.statuses.update');

    Route::post('usulan/documents', 'ProposalController@document')->name('proposals.documents');
    Route::post('usulan/criterias', 'ProposalController@updatePivotCriteria')->name('proposals.criterias');
    Route::get('usulan/download/{proposal}/all', 'ProposalController@downloadAll')->name('proposals.documents.download.all');
    Route::get('usulan/download/{proposal}/{criteria}', 'ProposalController@download')->name('proposals.documents.download');
    Route::get('usulan/data', 'ProposalController@data')->name('proposals.data');
    Route::get('usulan', ['uses' => 'ProposalController@index', 'as' => 'proposals.index']);
    Route::put('usulan/{usulan}', 'ProposalController@update')->name('proposals.update');
    Route::get('usulan/{usulan}/edit', ['uses' => 'ProposalController@edit', 'as' => 'proposals.edit']);
    Route::delete('usulan/{usulan}', ['uses' => 'ProposalController@destroy', 'as' => 'proposals.destroy']);
    Route::get('usulan/{usulan}/status/edit', ['uses' => 'ProposalController@editStatus'])->name('proposals.status.edit');
    Route::put('usulan/{usulan}/status', ['uses' => 'ProposalController@updateStatus'])->name('proposals.status.update');

    Route::post('comments', 'CommentController@store')->name('comments.store');

    // Shortlist
    Route::get('usulan/{id}/shortlist', 'ShortlistController@create')->name('shortlists.create');
    Route::get('shortlist/data', 'ShortlistController@data')->name('shortlists.data');

app/Http/Controllers/GuidanceController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\GuidanceDataTable;
use App\Models\Document;
use Illuminate\Http\Request;

class GuidanceController extends Controller
{
    protected $identifier = 'pedoman';

    public function index(GuidanceDataTable $dataTable)
    {
        $title = 'Pedoman';

        return $dataTable->render('guidance.index', [
            'title'      => $title,
            'identifier' => $this->identifier,
        ]);
    }

    public function create(Request $request)
    {
        if ($request->ajax()) {
            return response()->json([
                'title'  => 'Pedoman baru',
                'body'   => view('guidance.modal.create')
                    ->with([
                        'identifier' => $this->identifier
                    ])
                    ->render(),
                'footer' => view('guidance.modal.footer')
                    ->with('identifier', $this->identifier)
                    ->render()
            ]);
        } else {
            return view('guidance.create');
        }
    }

    public function store(Request $request)
    {
        $validator = validator($request->all(), [
            'title' => 'required',
            'description' => 'required',
            'file'  => 'required'
        ]);

        if ($validator->fails()) {
            if ($request->ajax()) {
                return response()->json($validator->errors(), 400);
            }
        }

        return Document::create([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'file' => $request->get('file'),
            'filename' => $request->get('file_name'),
        ]);
    }

    public function edit($id, Request $request)
    {

        $document = Document::find($id);

//        if ($request->ajax()) {
        return response()->json([
            'title'  => "Ubah pedoman",
            'body'   => view('guidance.modal.edit')
                ->with([
                    'guidance'   => $document,
                    'identifier' => $this->identifier
                ])
                ->render(),
            'footer' => view('guidance.modal.footer')
                ->with('identifier', $this->identifier)
                ->render()
        ]);
//        } else {
//            return view('faq.edit');
//        }
    }

    public function update(Request $request, $id)
    {
        $document = Document::find($id);

        $validator = validator($request->all(), [
            'title' => 'required',
            'description' => 'required',
            'file'  => 'required'
        ]);

        if ($validator->fails()) {
            if ($request->ajax()) {
                return response()->json($validator->errors(), 400);
            }
        }

        $document->title = $request->get('title');
        $document->description = $request->get('description');
        $document->file = $request->get('file');
        $document->filename = $request->get('file_name');
        $document->save();

        if ($request->ajax()) {
            return response()->json([]);
        }

        return redirect()->route('guidance.index');

    }

    public function destroy($id)
    {
        return Document::destroy($id);
    }
}

resources/views/guidance/modal/create.blade.php
<form action="{{route('guidance.store')}}" id="{{$identifier}}" method="post">
    {{csrf_field()}}

    <div class="form-group">
        <label for="title" class="control-label">Judul</label>
        <input type="text" id="title" class="form-control" name="title" placeholder="Judul" aria-describedby="help-block-title" />
        <div class="help-block" id="help-block-title"></div>
    </div>

    <div class="form-group">
        <label for="description" class="control-label">Deskripsi</label>
        <textarea id="description" class="form-control" name="description" placeholder="Deskripsi" aria-describedby="help-block-description"></textarea>

        <div class="help-block" id="help-block-description"></div>
    </div>

    <div class="form-group">
        <label for="file" class="control-label">File</label>
        <div class="col-progress col-download">
            <div class="wrapper margin-bottom-15"></div>
        </div>
        <input type="file" id="file" name="" placeholder="File" class="simple-upload">
        <input type="hidden" name="file" value="" id="location-file">
        <input type="hidden" name="file_name" value="" id="filename-file">
        <div class="help-block" id="help-block-file"></div>
    </div>
</form>


<script>
    $('.simple-upload').change(function () {

        var $this = $(this);
        var $thisProgressStatus =   $this.parent().find('.col-progress');
        var $thisDownload =   $this.parent().find('.col-download');
        var $attachmentField = $this.parent().find('#location-file');
        var $attachmentNameField = $this.parent().find('#filename-file');


        $(this).simpleUpload('{{route('assets.upload')}}', {
            name: 'file',
            data: {
                _token: '{{csrf_token()}}'
            },
            progress: function(progress) {
                var htmlProgress = '<div class="progress" style="margin-bottom: 0;"> ' +
                        '<div class="progress-bar progress-bar-striped active " role="progressbar" aria-valuenow="'+Math.round(progress)+'" aria-valuemin="0" aria-valuemax="100" style="width: '+Math.round(progress)+'%"> ' +
                        '<span class="">'+Math.round(progress)+'%</span> ' +
                        '</div> ' +
                        '</div>';
                $thisProgressStatus.find('.wrapper').html(htmlProgress);
            },
            success: function(data) {

                var htmlLink = data.file_name;

                $thisDownload.find('.progress').fadeOut();
                $thisDownload.find('.wrapper').html(htmlLink).css({display:'none'});
                $thisDownload.find('.wrapper').fadeIn();

                $attachmentField.val(data.location);
                $attachmentNameField.val(data.file_name);
            },
            error: function(error) {
                console.log(error);
                $thisDownload.find('.progress').fadeOut();
                $thisDownload.find('.wrapper')
                        .html('<span class="text-danger">'+error.message+'!</span>')
                        .css({display:'none'});
                $thisDownload.find('.wrapper').fadeIn();
            }
        });
    });
</script>

resources/views/guidance/modal/edit.blade.php
<form action="{{route('guidance.update', $guidance->id)}}" id="{{$identifier}}" method="post">
    {{csrf_field()}}
    {{method_field("PUT")}}
    <div class="form-group">
        <label for="title" class="control-label">Judul</label>
        <input type="text" id="title" class="form-control" name="title" placeholder="Judul" aria-describedby="help-block-title" value="{{$guidance->title}}" />
        <div class="help-block" id="help-block-title"></div>
    </div>

    <div class="form-group">
        <label for="description" class="control-label">Deskripsi</label>
        <textarea id="description" class="form-control" name="description" placeholder="Deskripsi" aria-describedby="help-block-description">{{$guidance->description}}</textarea>

        <div class="help-block" id="help-block-description"></div>
    </div>

    <div class="form-group">
        <label for="file" class="control-label">File</label>
        <div class="col-progress col-download">
            <div class="wrapper margin-bottom-15">{{$guidance->filename}}</div>
        </div>
        <input type="file" id="file" name="" placeholder="File" class="simple-upload">
        <input type="hidden" name="file" value="{{$guidance->file}}" id="location-file" >
        <input type="hidden" name="file_name" value="{{$guidance->filename}}" id="filename-file">
        <div class="help-block" id="help-block-file"></div>
    </div>
</form>
<script>
    $('.simple-upload').change(function () {

        var $this = $(this);
        var $thisProgressStatus =   $this.parent().find('.col-progress');
        var $thisDownload =   $this.parent().find('.col-download');
        var $attachmentField = $this.parent().find('#location-file');
        var $attachmentNameField = $this.parent().find('#filename-file');


        $(this).simpleUpload('{{route('assets.upload')}}', {
            name: 'file',
            data: {
                _token: '{{csrf_token()}}'
            },
            progress: function(progress) {
                var htmlProgress = '<div class="progress" style="margin-bottom: 0;"> ' +
                        '<div class="progress-bar progress-bar-striped active " role="progressbar" aria-valuenow="'+Math.round(progress)+'" aria-valuemin="0" aria-valuemax="100" style="width: '+Math.round(progress)+'%"> ' +
                        '<span class="">'+Math.round(progress)+'%</span> ' +
                        '</div> ' +
                        '</div>';
                $thisProgressStatus.find('.wrapper').html(htmlProgress);
            },
            success: function(data) {

                var htmlLink = data.file_name;

                $thisDownload.find('.progress').fadeOut();
                $thisDownload.find('.wrapper').html(htmlLink).css({display:'none'});
                $thisDownload.find('.wrapper').fadeIn();

                $attachmentField.val(data.location);
                $attachmentNameField.val(data.file_name);
            },
            error: function(error) {
                console.log(error);
                $thisDownload.find('.progress').fadeOut();
                $thisDownload.find('.wrapper')
                        .html('<span class="text-danger">'+error.message+'!</span>')
                        .css({display:'none'});
                $thisDownload.find('.wrapper').fadeIn();
            }
        });
    });
</script>

resources/views/guidance/modal/footer.blade.php
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
<button type="button" class="btn btn-primary" onclick="saveForm(this)"
        data-identifier="{{$identifier}}">Save</button>